#!/bin/bash

useradd -m cc

adduser cc sudo

/lib/systemd/systemd-udevd --debug & /sbin/udevadm trigger

xinit /usr/bin/xterm -fa 'Monospace' -fs 14 -bg black -fg white -e "su -l cc -c '/bin/sh -c i3' " -- /usr/bin/X :0
