#!/bin/bash

read -p "input username :" name
egrep "^$name" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
    echo "$name exists!"
else
    useradd -m $name
    adduser $name sudo
    passwd $name
fi

# useradd -m $name
# adduser $name sudo
# passwd $name

/lib/systemd/systemd-udevd --debug & /sbin/udevadm trigger

xinit /usr/bin/xterm -fa 'Monospace' -fs 14 -bg black -fg white -e "su -l $name -c '/bin/sh -c i3' " -- /usr/bin/X :0
